import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button, Row, Col, Modal } from "react-bootstrap";
import ComponentLibraryList from "@/components/ComponentLibraryList";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1>AN H1 Just inside the Container Component</h1>
        <Row>
          Here's some text just inside Row 1.
          <Col>Col 1 of 4</Col>
          <Col>Col 2 of 4</Col>
          <Col>Col 3 of 4</Col>
          <Col>Col 4 of 4</Col>
        </Row>
        <Row>
          Here's some text just inside Row 2.
          <Col>Col 1 of 4</Col>
          <Col>Col 2 of 4</Col>
          <Col>Col 3 of 4</Col>
          <Col>Col 4 of 4</Col>
        </Row>
        <br />
        <Row>
          <Modal.Dialog>
            <Modal.Header>
              <Modal.Title>Did we get a working title ?</Modal.Title>
            </Modal.Header>
            <Modal.Body>
              <ComponentLibraryList />
              <Button variant="outline-primary">
                Please don't click me Ever
              </Button>
            </Modal.Body>
          </Modal.Dialog>
        </Row>
      </main>
    </>
  );
}
