import { useState } from 'react'
import Head from 'next/head'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';
import Divider from '@mui/material/Divider';

import FormControl from '@mui/material/FormControl';
import FormLabel from '@mui/material/FormLabel';
import FormControlLabel from '@mui/material/FormControlLabel';
import Grid from '@mui/material/Grid';

import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';
import Rating from '@mui/material/Rating';

import TextField from '@mui/material/TextField';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';


// own components
import AdaptationReviewCard from '@/components/AdaptationReviewCard';

// own logic / helpers
import { getReviews, postReview } from '../utils/api/reviews.js'


export default function Home() {

  const [reviews, setReviews] = useState([])

  const [title, setTitle] = useState("")
  const [comments, setComments] = useState("")
  const [rating, setRating] = useState(0)

  const loadAllReviewsButton = () => {
    getReviews().then((data) =>{
      setReviews(data)
    })
  }

  const handleSubmit = (event) => {
    event.preventDefault()
    postReview({
      title,
      comment: comments,
      rating
    }).then((data)=> {
      setReviews([data, ...reviews])
    })
  }

  return (
    <div>
      <Head>
        <title>Adaptation Reviews.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            Adaptations Reviews
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="md">
          <form
            onSubmit={handleSubmit}
          >
            <Grid container spacing={3}>
              <Grid item xs={12} sm={12}>
                <TextField
                  id="title"
                  name="title"
                  label="Adaptation Title"
                  fullWidth
                  variant="standard"
                  value={title}
                  onChange={(e) => {setTitle(e.target.value)}}
                />
              </Grid>
              <Grid item xs={12} sm={12}>
                <TextField
                  id="review-comments"
                  name="review-comments"
                  label="Comments"
                  fullWidth
                  variant="standard"
                  value={comments}
                  onChange={(e) => {setComments(e.target.value)}}
                />
              </Grid>
              <Grid item xs={12} sm={12}>
                <FormControl>
                  <FormLabel id="adaptation-rating">Rating</FormLabel>
                  <Rating
                    id="review-rating"
                    name="review-rating"
                    max={10}
                    value={rating}
                    onChange={(e) => {setRating(e.target.value)}}
                  />
               </FormControl>
              </Grid>
              <Grid item xs={12} sm={12}>
                <Button
                  variant="contained"
                  type="submit"
                >
                  Add New Review
                </Button>
              </Grid>
            </Grid>
          </form>
          <Box
            sx={{
              py: 2,
            }}
          >
            <Button
              variant="contained"
              onClick={loadAllReviewsButton}
            >
              Load All Current Reviews
            </Button>
          </Box>
          <Divider
            sx={{ 
              py: 4,
            }}
          />
          {reviews.map((adaptation, index) => {
            return <AdaptationReviewCard
              key={index}
              id={adaptation.id}
              rating={adaptation.rating}
              title={adaptation.title}
              comment={adaptation.comment}
            />
          })}

        </Container>
      </main>
    </div>
  );
}
