import { useState } from 'react';

import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';

import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemText from '@mui/material/ListItemText';

import ListInput from '@/components/ListInput';
import ListSubmitButton from '@/components/ListSubmitButton';


export default function Home() {

  const [textValue, setTextValue] = useState("")
  const [allTodos, setAllTodos] = useState([])

  const onTodoTextChange = (event) => {
    setTextValue(event.target.value)
  }

  const onAddTodoClick = () => {
   const newAllTodoList = [...allTodos, textValue]
   console.log(newAllTodoList)
   setAllTodos(newAllTodoList)
   setTextValue("")
  }

  const submitHandler = (event) => {
    event.preventDefault()
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page}`}
      >
        <main className={styles.main}>
          <form
            onSubmit={submitHandler}
          >
            <Container
              maxWidth="md"
              component="main"
              sx={{ mt: 10 }}
            >
              <Grid container spacing={2}>

                <ListInput
                  changeHandler={onTodoTextChange}
                  inputValue={textValue}
                />


                <ListSubmitButton
                  clickHandler={onAddTodoClick}
                />


                <Grid item xs={12}>
                  <List sx={{ width: "100%" }}>
                    {allTodos.map((todoItem, index) => {
                      return <ListItem key={index}>
                        <ListItemText>
                          <Typography variant="p" component="div">
                            {todoItem}
                          </Typography>
                        </ListItemText>
                      </ListItem>
                    })}
                  </List>
                </Grid>

              </Grid>
            </Container>
          </form>
        </main>
      </div>
    </>
  );
}
